/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.4
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2020 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "UART.h"
#include "ADC_DelSig.h"
#include "Clock_Timer_ADC.h"
#include "Timer.h"
#include "R_Pin_aliases.h"
#include "R_Pin.h"
#include "isr_ADC.h"
#include "AMux.h"
#include "R_Pin_1_aliases.h"
#include "R_Pin_1.h"
#include "R_Pin_2_aliases.h"
#include "R_Pin_2.h"
#include "R_Pin_3_aliases.h"
#include "R_Pin_3.h"
#include "UART_BT.h"
#include "Pin_LED_aliases.h"
#include "Pin_LED.h"
#include "Pin_BATT_aliases.h"
#include "Pin_BATT.h"
#include "UART_IntClock.h"
#include "ADC_DelSig_AMux.h"
#include "ADC_DelSig_Ext_CP_Clk.h"
#include "ADC_DelSig_IRQ.h"
#include "ADC_DelSig_theACLK.h"
#include "UART_BT_IntClock.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"
#include "cy_em_eeprom.h"

/*[]*/

